package com.lepu.algorithm.restingecg.gri;


/**
 * Maintains the global scalar measurements that are generated by the C analysis
 * library.
 * 
 * @author Brian Devine
 *
 */
public class GlobalMeas {
	// --------------------------------------------------------------------------	
	private static final String TAG = "MyActivity-GlobalMeas";
	// --------------------------------------------------------------------------	
	
	short	QrsFrontalAxis;
	short	PFrontalAxis;
	short	STFrontalAxis;
	short	TFrontalAxis;
	short	QrsPsdoVec48SpatVel;
	short	QrsPsdoVec58SpatVel;
	short	QrsPsdoVec68SpatVel;
	short	QrsPsdoVec78SpatVel;
	short	QrsPsdoVecMaxAmpl;
	short	DeltaWaveAmpI;
	short	DeltaWaveAmpII;
	short	DeltaWaveAmpIII;
	short	DeltaWaveAmpaVF;
	short	DeltaWaveFrontalAxis;
	// @NOTIFY: SPARE 1
	
	short	OverallPOnset;
	short	OverallPTermination;
	short	OverallQrsOnset;
	short	OverallQrsTermination;
	short	OverallTOnset;
	short	OverallTTermination;
	short	AtrialPacerPeak;
	short	VentricularPacerPeak;
	short	HeartRateVariability;
	short	StdDevNormRRIntervals;
	short	LVHscore;
	short	LVstrain;
	short	DefaultAge;	// C unsigned data type
	short	DefaultSex;
	short	DefaultRace;

	short	OverallPDuration;
	short	OverallQrsDuration;
	short	OverallSTDuration;
	short	OverallTDuration;
	short	RmaxaVR;
	short	RmaxaVL;
	short	SAmpV1;
	short	RAmpV5;
	short	SAmpV1PlusRAmpV5;
	// @NOTIFY: SPARE 6
	
	short	OverallPRInterval;
	short	OverallQTInterval;
	short	HeartRate;
	short	PTerminalForceInV1;
	short	QTDispersion;
	short	QTc;
	short	Flags;
	short	QTcHodge;
	short	QTcBazett;
	short	QTcFridericia;
	short	QTcFramingham;
	short	SinusRate;
	short	SinusAverageRR;
	short	VentRate;
	short	VentAverageRR;
	

	// ----------------------------------------------------------------------
	// METHODS
	// ----------------------------------------------------------------------

	/**
	 * Creates instance of GlobalMeas and initialises all values to 
	 * GRI_UNDEFINED.
	 */
	public GlobalMeas()
	{


		this.QrsFrontalAxis        = RestingEcg.GRI_UNDEFINED;
		this.PFrontalAxis          = RestingEcg.GRI_UNDEFINED;
		this.STFrontalAxis         = RestingEcg.GRI_UNDEFINED;
		this.TFrontalAxis          = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec48SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec58SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec68SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec78SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVecMaxAmpl     = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpI         = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpII        = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpIII       = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpaVF       = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveFrontalAxis  = RestingEcg.GRI_UNDEFINED;
		// SPARE
		
		this.OverallPOnset         = RestingEcg.GRI_UNDEFINED;
		this.OverallPTermination   = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsOnset       = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsTermination = RestingEcg.GRI_UNDEFINED;
		this.OverallTOnset         = RestingEcg.GRI_UNDEFINED;
		this.OverallTTermination   = RestingEcg.GRI_UNDEFINED;
		this.AtrialPacerPeak       = RestingEcg.GRI_UNDEFINED;
		this.VentricularPacerPeak  = RestingEcg.GRI_UNDEFINED;
		this.HeartRateVariability  = RestingEcg.GRI_UNDEFINED;
		this.StdDevNormRRIntervals = RestingEcg.GRI_UNDEFINED;
		this.LVHscore              = RestingEcg.GRI_UNDEFINED;
		this.LVstrain              = RestingEcg.GRI_UNDEFINED;
		this.DefaultAge            = RestingEcg.GRI_UNDEFINED;	// C unsigned data type
		this.DefaultSex            = RestingEcg.GRI_UNDEFINED;
		this.DefaultRace           = RestingEcg.GRI_UNDEFINED;
		
		this.OverallPDuration      = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsDuration    = RestingEcg.GRI_UNDEFINED;
		this.OverallSTDuration     = RestingEcg.GRI_UNDEFINED;
		this.OverallTDuration      = RestingEcg.GRI_UNDEFINED;
		this.RmaxaVR               = RestingEcg.GRI_UNDEFINED;
		this.RmaxaVL               = RestingEcg.GRI_UNDEFINED;
		
		this.OverallPRInterval     = RestingEcg.GRI_UNDEFINED;
		this.OverallQTInterval     = RestingEcg.GRI_UNDEFINED;
		this.HeartRate             = RestingEcg.GRI_UNDEFINED;
		this.PTerminalForceInV1    = RestingEcg.GRI_UNDEFINED;
		this.QTDispersion          = RestingEcg.GRI_UNDEFINED;
		this.QTc                   = RestingEcg.GRI_UNDEFINED;
		this.Flags                 = RestingEcg.GRI_UNDEFINED;
		this.QTcHodge              = RestingEcg.GRI_UNDEFINED;
		this.QTcBazett             = RestingEcg.GRI_UNDEFINED;
		this.QTcFridericia         = RestingEcg.GRI_UNDEFINED;
		this.QTcFramingham         = RestingEcg.GRI_UNDEFINED;
		this.SinusRate             = RestingEcg.GRI_UNDEFINED;
		this.SinusAverageRR        = RestingEcg.GRI_UNDEFINED;
		this.VentRate              = RestingEcg.GRI_UNDEFINED;
		this.VentAverageRR         = RestingEcg.GRI_UNDEFINED;
	}
	
	// ----------------------------------------------------------------------

	public void setQrsFrontalAxis( short Value )
	{
		QrsFrontalAxis        = Value;
	}

	// ----------------------------------------------------------------------

	public void setPFrontalAxis( short Value )
	{
		PFrontalAxis        = Value;
	}
	
	// ----------------------------------------------------------------------

	public void setSTFrontalAxis( short Value )
	{
		STFrontalAxis        = Value;
	}

	// ----------------------------------------------------------------------

	public void setTFrontalAxis( short Value )
	{
		TFrontalAxis        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQrsPsdoVec48SpatVel( short Value )
	{
		QrsPsdoVec48SpatVel        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQrsPsdoVec58SpatVel( short Value )
	{
		QrsPsdoVec58SpatVel        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQrsPsdoVec68SpatVel( short Value )
	{
		QrsPsdoVec68SpatVel        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQrsPsdoVec78SpatVel( short Value )
	{
		QrsPsdoVec78SpatVel        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQrsPsdoVecMaxAmpl( short Value )
	{
		QrsPsdoVecMaxAmpl        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallPOnset( short Value )
	{
		OverallPOnset        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallPTermination( short Value )
	{
		OverallPTermination        = Value;
	}

	// ----------------------------------------------------------------------
	
	public void setOverallQrsOnset( short Value )
	{
		OverallQrsOnset        = Value;
	}
	
	// ----------------------------------------------------------------------

	public void setOverallQrsTermination( short Value )
	{
		OverallQrsTermination        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallTOnset( short Value )
	{
		OverallTOnset        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallTTermination( short Value )
	{
		OverallTTermination        = Value;
	}

	// ----------------------------------------------------------------------

	public void setHeartRateVariability( short Value )
	{
		HeartRateVariability        = Value;
	}

	// ----------------------------------------------------------------------

	public void setStdDevNormRRIntervals( short Value )
	{
		StdDevNormRRIntervals        = Value;
	}

	// ----------------------------------------------------------------------

	public void setLVHscore( short Value )
	{
		LVHscore        = Value;
	}

	// ----------------------------------------------------------------------

	public void setLVstrain( short Value )
	{
		LVstrain = Value;
	}

	// ----------------------------------------------------------------------

	public void setDefaultAge( short Value )
	{
		DefaultAge = Value;	// C unsigned data type
	}

	// ----------------------------------------------------------------------

	public void setDefaultSex( short Value )
	{
		DefaultSex        = Value;
	}

	// ----------------------------------------------------------------------

	public void setDefaultRace( short Value )
	{
		DefaultRace        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallPDuration( short Value )
	{
		OverallPDuration        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallQrsDuration( short Value )
	{
		OverallQrsDuration        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallSTDuration( short Value )
	{
		OverallSTDuration        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallTDuration( short Value )
	{
		OverallTDuration        = Value;
	}

	// ----------------------------------------------------------------------

	public void setRmaxaVR( short Value )
	{
		RmaxaVR        = Value;
	}

	// ----------------------------------------------------------------------

	public void setRmaxaVL( short Value )
	{
		RmaxaVL        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallPRInterval( short Value )
	{
		OverallPRInterval        = Value;
	}

	// ----------------------------------------------------------------------

	public void setOverallQTInterval( short Value )
	{
		OverallQTInterval        = Value;
	}

	// ----------------------------------------------------------------------

	public void setHeartRate( short Value )
	{
		HeartRate        = Value;
	}

	// ----------------------------------------------------------------------
	
	public void setPTerminalForceInV1( short Value )
	{
		PTerminalForceInV1        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTDispersion( short Value )
	{
		QTDispersion        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTc( short Value )
	{
		QTc        = Value;
	}

	// ----------------------------------------------------------------------

	public void setFlags( short Value )
	{
		Flags        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTcHodge( short Value )
	{
		QTcHodge        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTcBazett( short Value )
	{
		QTcBazett        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTcFridericia( short Value )
	{
		QTcFridericia        = Value;
	}

	// ----------------------------------------------------------------------

	public void setQTcFramingham( short Value )
	{
		QTcFramingham        = Value;
	}

	// ----------------------------------------------------------------------

	public void setSinusRate( short Value )
	{
		SinusRate = Value;
	}

	// ----------------------------------------------------------------------


	public void setSinusAverageRR( short Value )
	{
		SinusAverageRR        = Value;
	}

	// ----------------------------------------------------------------------

	public void setVentRate( short Value )
	{
		VentRate = Value;
	}

	// ----------------------------------------------------------------------

	public void setVentAverageRR( short Value )
	{
		VentAverageRR = Value;
	}

	// ----------------------------------------------------------------------

	public short getQrsFrontalAxis()
	{
		return QrsFrontalAxis;
	}

	// ----------------------------------------------------------------------

	public short getPFrontalAxis()
	{
		return PFrontalAxis;
	}

	// ----------------------------------------------------------------------

	public short getSTFrontalAxis()
	{
		return STFrontalAxis;
	}

	// ----------------------------------------------------------------------

	public short getTFrontalAxis()
	{
		return TFrontalAxis;
	}

	// ----------------------------------------------------------------------

	public short getQrsPsdoVec48SpatVel()
	{
		return QrsPsdoVec48SpatVel;
	}

	// ----------------------------------------------------------------------

	public short getQrsPsdoVec58SpatVel()
	{
		return QrsPsdoVec58SpatVel;
	}

	// ----------------------------------------------------------------------

	public short getQrsPsdoVec68SpatVel()
	{
		return QrsPsdoVec68SpatVel;
	}

	// ----------------------------------------------------------------------

	public short getQrsPsdoVec78SpatVel()
	{
		return QrsPsdoVec78SpatVel;
	}

	// ----------------------------------------------------------------------

	public short getQrsPsdoVecMaxAmpl()
	{
		return QrsPsdoVecMaxAmpl;
	}

	// ----------------------------------------------------------------------

	public short getOverallPOnset()
	{
		return OverallPOnset;
	}

	// ----------------------------------------------------------------------

	public short getOverallPTermination()
	{
		return OverallPTermination;
	}

	// ----------------------------------------------------------------------

	public short getOverallQrsOnset()
	{
		return OverallQrsOnset;
	}

	// ----------------------------------------------------------------------

	public short getOverallQrsTermination()
	{
		return OverallQrsTermination;
	}

	// ----------------------------------------------------------------------

	public short getOverallTOnset()
	{
		return OverallTOnset;
	}

	// ----------------------------------------------------------------------

	public short getOverallTTermination()
	{
		return OverallTTermination;
	}

	// ----------------------------------------------------------------------

	public short getHeartRateVariability()
	{
		return HeartRateVariability;
	}

	// ----------------------------------------------------------------------

	public short getStdDevNormRRIntervals()
	{
		return StdDevNormRRIntervals;
	}

	// ----------------------------------------------------------------------

	public short getLVHscore()
	{
		return LVHscore;
	}

	// ----------------------------------------------------------------------

	public short getLVstrain()
	{
		return LVstrain;
	}

	// ----------------------------------------------------------------------

	public short getDefaultAge()
	{
		return DefaultAge;	// C unsigned data type
	}

	// ----------------------------------------------------------------------

	public short getDefaultSex()
	{
		return DefaultSex;
	}

	// ----------------------------------------------------------------------

	public short getDefaultRace()
	{
		return DefaultRace;
	}

	// ----------------------------------------------------------------------

	public short getOverallPDuration()
	{
		return OverallPDuration;
	}

	// ----------------------------------------------------------------------

	public short getOverallQrsDuration()
	{
		return OverallQrsDuration;
	}

	// ----------------------------------------------------------------------

	public short getOverallSTDuration()
	{
		return OverallSTDuration;
	}

	// ----------------------------------------------------------------------

	public short getOverallTDuration()
	{
		return OverallTDuration;
	}

	// ----------------------------------------------------------------------

	public short getRmaxaVR()
	{
		return RmaxaVR;
	}

	// ----------------------------------------------------------------------

	public short getRmaxaVL()
	{
		return RmaxaVL;
	}

	// ----------------------------------------------------------------------

	
	public short getOverallPRInterval()
	{
		return OverallPRInterval;
	}
	
	// ----------------------------------------------------------------------

	public short getOverallQTInterval()
	{
		return OverallQTInterval;
	}

	// ----------------------------------------------------------------------

	public short getHeartRate()
	{
		return HeartRate;
	}

	// ----------------------------------------------------------------------

	public short getPTerminalForceInV1()
	{
		return PTerminalForceInV1;
	}

	// ----------------------------------------------------------------------

	public short getQTDispersion()
	{
		return QTDispersion;
	}

	// ----------------------------------------------------------------------
	
	/**
	 * Retrieves the QTc interval (ms) that is used by the contour diagnostic
	 * analysis.
	 * defaults from the measurement matrix.
	 * 
	 * @return	The 16-bit value containing the bit-wise flags.
	 * @see ControlInfo#setQTcHodge() setQTcHodge()
	 */
	public short getQTc()
	{
		return QTc;
	}

	// ----------------------------------------------------------------------
	
	/**
	 * Retrieves the status flags for P wave, Qrs axis and demographic
	 * defaults from the measurement matrix.
	 * 
	 * @return	The 16-bit value containing the bit-wise flags. 
	 */
	public short getFlags()
	{
		return Flags;
	}

	// ----------------------------------------------------------------------

	/**
	 * Retrieves the QTc interval (ms) computed using the Hodge QTc
	 * formula.
	 * 
	 * @return	The QTc interval in milliseconds.
	 */
	public short getQTcHodge()
	{
		return QTcHodge;
	}

	// ----------------------------------------------------------------------

	/**
	 * Retrieves the QTc interval (ms) computed using the Bazett QTc
	 * formula.
	 * 
	 * @return	The QTc interval in milliseconds.
	 */
	public short getQTcBazett()
	{
		return QTcBazett;
	}

	// ----------------------------------------------------------------------

	/**
	 * Retrieves the QTc interval (ms) computed using the Fridericia QTc
	 * formula.
	 * 
	 * @return	The QTc interval in milliseconds.
	 */
	public short getQTcFridericia()
	{
		return QTcFridericia;
	}

	// ----------------------------------------------------------------------

	/**
	 * Retrieves the QTc interval (ms) computed using the Framingham QTc
	 * formula.
	 * 
	 * @return	The QTc interval in milliseconds.
	 */
	public short getQTcFramingham()
	{
		return QTcFramingham;
	}

	// ----------------------------------------------------------------------

	public short getSinusRate()
	{
		return SinusRate;
	}

	// ----------------------------------------------------------------------

	public short getSinusAverageRR()
	{
		return SinusAverageRR;
	}

	// ----------------------------------------------------------------------

	public short getVentRate()
	{
		return VentRate;
	}

	// ----------------------------------------------------------------------

	public short getVentAverageRR()
	{
		return VentAverageRR;
	}
	
	// ----------------------------------------------------------------------
	
	/**
	 * Reset all measurements to {@link RestingEcg#GRI_UNDEFINED}.
	 */
	public void clearMeasurements()
	{
		this.QrsFrontalAxis        = RestingEcg.GRI_UNDEFINED;
		this.PFrontalAxis          = RestingEcg.GRI_UNDEFINED;
		this.STFrontalAxis         = RestingEcg.GRI_UNDEFINED;
		this.TFrontalAxis          = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec48SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec58SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec68SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVec78SpatVel   = RestingEcg.GRI_UNDEFINED;
		this.QrsPsdoVecMaxAmpl     = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpI         = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpII        = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpIII       = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveAmpaVF       = RestingEcg.GRI_UNDEFINED;
		this.DeltaWaveFrontalAxis  = RestingEcg.GRI_UNDEFINED;
		// SPARE
		
		this.OverallPOnset         = RestingEcg.GRI_UNDEFINED;
		this.OverallPTermination   = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsOnset       = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsTermination = RestingEcg.GRI_UNDEFINED;
		this.OverallTOnset         = RestingEcg.GRI_UNDEFINED;
		this.OverallTTermination   = RestingEcg.GRI_UNDEFINED;
		this.AtrialPacerPeak       = RestingEcg.GRI_UNDEFINED;
		this.VentricularPacerPeak  = RestingEcg.GRI_UNDEFINED;
		this.HeartRateVariability  = RestingEcg.GRI_UNDEFINED;
		this.StdDevNormRRIntervals = RestingEcg.GRI_UNDEFINED;
		this.LVHscore              = RestingEcg.GRI_UNDEFINED;
		this.LVstrain              = RestingEcg.GRI_UNDEFINED;
		this.DefaultAge            = RestingEcg.GRI_UNDEFINED;	// C unsigned data type
		this.DefaultSex            = RestingEcg.GRI_UNDEFINED;
		this.DefaultRace           = RestingEcg.GRI_UNDEFINED;
		
		this.OverallPDuration      = RestingEcg.GRI_UNDEFINED;
		this.OverallQrsDuration    = RestingEcg.GRI_UNDEFINED;
		this.OverallSTDuration     = RestingEcg.GRI_UNDEFINED;
		this.OverallTDuration      = RestingEcg.GRI_UNDEFINED;
		this.RmaxaVR               = RestingEcg.GRI_UNDEFINED;
		this.RmaxaVL               = RestingEcg.GRI_UNDEFINED;
		
		this.OverallPRInterval     = RestingEcg.GRI_UNDEFINED;
		this.OverallQTInterval     = RestingEcg.GRI_UNDEFINED;
		this.HeartRate             = RestingEcg.GRI_UNDEFINED;
		this.PTerminalForceInV1    = RestingEcg.GRI_UNDEFINED;
		this.QTDispersion          = RestingEcg.GRI_UNDEFINED;
		this.QTc                   = RestingEcg.GRI_UNDEFINED;
		this.Flags                 = RestingEcg.GRI_UNDEFINED;
		this.QTcHodge              = RestingEcg.GRI_UNDEFINED;
		this.QTcBazett             = RestingEcg.GRI_UNDEFINED;
		this.QTcFridericia         = RestingEcg.GRI_UNDEFINED;
		this.QTcFramingham         = RestingEcg.GRI_UNDEFINED;
		this.SinusRate             = RestingEcg.GRI_UNDEFINED;
		this.SinusAverageRR        = RestingEcg.GRI_UNDEFINED;
		this.VentRate              = RestingEcg.GRI_UNDEFINED;
		this.VentAverageRR         = RestingEcg.GRI_UNDEFINED;		
	}

	@Override
	public String toString() {
		return "GlobalMeas{" +
				"QrsFrontalAxis=" + QrsFrontalAxis +
				", PFrontalAxis=" + PFrontalAxis +
				", STFrontalAxis=" + STFrontalAxis +
				", TFrontalAxis=" + TFrontalAxis +
				", QrsPsdoVec48SpatVel=" + QrsPsdoVec48SpatVel +
				", QrsPsdoVec58SpatVel=" + QrsPsdoVec58SpatVel +
				", QrsPsdoVec68SpatVel=" + QrsPsdoVec68SpatVel +
				", QrsPsdoVec78SpatVel=" + QrsPsdoVec78SpatVel +
				", QrsPsdoVecMaxAmpl=" + QrsPsdoVecMaxAmpl +
				", DeltaWaveAmpI=" + DeltaWaveAmpI +
				", DeltaWaveAmpII=" + DeltaWaveAmpII +
				", DeltaWaveAmpIII=" + DeltaWaveAmpIII +
				", DeltaWaveAmpaVF=" + DeltaWaveAmpaVF +
				", DeltaWaveFrontalAxis=" + DeltaWaveFrontalAxis +
				", OverallPOnset=" + OverallPOnset +
				", OverallPTermination=" + OverallPTermination +
				", OverallQrsOnset=" + OverallQrsOnset +
				", OverallQrsTermination=" + OverallQrsTermination +
				", OverallTOnset=" + OverallTOnset +
				", OverallTTermination=" + OverallTTermination +
				", AtrialPacerPeak=" + AtrialPacerPeak +
				", VentricularPacerPeak=" + VentricularPacerPeak +
				", HeartRateVariability=" + HeartRateVariability +
				", StdDevNormRRIntervals=" + StdDevNormRRIntervals +
				", LVHscore=" + LVHscore +
				", LVstrain=" + LVstrain +
				", DefaultAge=" + DefaultAge +
				", DefaultSex=" + DefaultSex +
				", DefaultRace=" + DefaultRace +
				", OverallPDuration=" + OverallPDuration +
				", OverallQrsDuration=" + OverallQrsDuration +
				", OverallSTDuration=" + OverallSTDuration +
				", OverallTDuration=" + OverallTDuration +
				", RmaxaVR=" + RmaxaVR +
				", RmaxaVL=" + RmaxaVL +
				", SAmpV1=" + SAmpV1 +
				", RAmpV5=" + RAmpV5 +
				", SAmpV1PlusRAmpV5=" + SAmpV1PlusRAmpV5 +
				", OverallPRInterval=" + OverallPRInterval +
				", OverallQTInterval=" + OverallQTInterval +
				", HeartRate=" + HeartRate +
				", PTerminalForceInV1=" + PTerminalForceInV1 +
				", QTDispersion=" + QTDispersion +
				", QTc=" + QTc +
				", Flags=" + Flags +
				", QTcHodge=" + QTcHodge +
				", QTcBazett=" + QTcBazett +
				", QTcFridericia=" + QTcFridericia +
				", QTcFramingham=" + QTcFramingham +
				", SinusRate=" + SinusRate +
				", SinusAverageRR=" + SinusAverageRR +
				", VentRate=" + VentRate +
				", VentAverageRR=" + VentAverageRR +
				'}';
	}
};

