package com.lepu.algorithm.restingecg.gri;


/**
 * Maintains the global vector measurements that are generated by the C analysis
 * library.
 * 
 * @author Brian Devine
 *
 */
public class GlobalVectMeas {
	// --------------------------------------------------------------------------	
	private static final String TAG = "MyActivity-GlobalVectMeas";
	// --------------------------------------------------------------------------	
		


}
