package com.lepu.algorithm.restingecg.gri;

import android.util.Log;

/**
 * Maintains the  serial result record
 * generated by the ECG software library. The Android build does not
 * support serial comparison and therefore this class simply serves as
 * a vehicle to return the serial data record from the analysis. Saving the
 * serial data record will allow serial comparison to be performed at
 * a later date when the feature is migrated to Android and is available
 * within the licensing model for the Glasgow ECG analysis software.
 * 
 * @author Brian Devine
 *
 */
public class SerialData {
	
	// ----------------------------------------------------------------------
	private static final String TAG = "MyActivity-SerialData";
	// ----------------------------------------------------------------------

	/**
	 * Size of serial data record as determined by the C ECG analysis library.
	 */
	static final short GRI_SERIAL_DATA_SIZE = 70;
	
	/**
	 * Bit-packed serial data record.
	 */
	short []	Data;
	
	
	// ----------------------------------------------------------------------
	// METHODS
	// ----------------------------------------------------------------------

	/**
	 * Creates and initialises an instance of the {@link SerialData}
	 * class.
	 */
	public SerialData()
	{
		this.Data = new short [GRI_SERIAL_DATA_SIZE];
	}
	
	// ----------------------------------------------------------------------

	/**
	 * Prints the contents of the {@link SerialData} instance to the debug
	 * output log.
	 */
	public void printContent()
	{
		short	i, colcount;
		String results;
		
		
		Log.d( TAG, "SerialData" );
		Log.d( TAG, "==========" );
		results = "";
		for ( i = 0, colcount = 1; i < GRI_SERIAL_DATA_SIZE; i++, colcount++ )
		{
			results = results + String.format( "%8d", Data[i] );
			if ( colcount % 10 == 0 )
			{
				Log.d( TAG, results + "\n" );
				results = "";
				colcount = 0;
			}
		}
		if ( !results.equals("") )
		{
			Log.d( TAG, results + "\n" );
		}

		Log.d( TAG, " " );
	}

}
